apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: qbittorrent
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/m0nsterrr/helm-charts/qbittorrent
  ref:
    digest: sha256:3f8fab7e3b7b6a61c155342ab1849e50e965181cdecd310967d1e45c596fbad6 # version 5.3.1+3f8fab7e3b7b
