router bgp 64513
 bgp router-id 192.168.1.1
 !
 network 192.168.2.0 mask 255.255.255.0
 network 192.168.10.0 mask 255.255.255.0
 !
 neighbor 169.254.0.1 remote-as 64514
 neighbor 169.254.0.1 description Tunnel0_GCP
 !
 neighbor 169.254.1.1 remote-as 64514
 neighbor 169.254.1.1 description Tunnel1_GCP
 !
 neighbor 192.168.2.10 remote-as 64512
 neighbor 192.168.2.10 description Cilium-Pi
 neighbor 192.168.2.10 timers 3 9
 !
 address-family ipv4
  neighbor 169.254.0.1 activate
  neighbor 169.254.0.1 soft-reconfiguration inbound
  neighbor 169.254.0.1 route-map ACCEPT_ROUTES in
  neighbor 169.254.0.1 route-map ADVERTISED_ROUTES out
  
  neighbor 169.254.1.1 activate
  neighbor 169.254.1.1 soft-reconfiguration inbound
  neighbor 169.254.1.1 route-map ACCEPT_ROUTES in
  neighbor 169.254.1.1 route-map ADVERTISED_ROUTES out
  
  neighbor 192.168.2.10 activate
  neighbor 192.168.2.10 soft-reconfiguration inbound
  neighbor 192.168.2.10 route-map ACCEPT_ROUTES in
  neighbor 192.168.2.10 route-map ADVERTISED_ROUTES out
 exit-address-family
 !
exit
!
route-map ACCEPT_ROUTES permit 10
 match ip address prefix-list ACCEPT_ALL
exit
!
route-map ADVERTISED_ROUTES permit 10
 match ip address prefix-list ADVERTISE_SPECIFIC
exit
!
ip prefix-list ACCEPT_ALL seq 5 permit any
!
ip prefix-list ADVERTISE_SPECIFIC seq 5 permit 192.168.2.0/24
ip prefix-list ADVERTISE_SPECIFIC seq 10 permit 192.168.10.0/24
