connections {
    gcp-site-to-site {
        local_addrs  = %any
        remote_addrs = 34.165.102.219
        version = 2
        mobike = no
        local {
            auth = psk
            id = 85.64.204.115
        }
        remote {
            auth = psk
            id = 34.165.102.219
        }
        children {
            gcp-subnets {
                local_ts  = 172.16.1.0/24
                remote_ts = 10.50.0.0/16, 10.1.0.0/20, 10.60.0.0/16
                start_action = start
                dpd_action = restart
            }
        }
    }
}

secrets {
    ike-gcp {
        id-local = 85.64.204.115
        id-remote = 34.165.102.219
        secret = "df8cG8ltYnXfemb3vQ3oRmbFvrOZXRdE"
    }
}
