persistence:
  media:
    enabled: false

volumeMounts:
  - name: jellyfin-media
    mountPath: /nfs-jellyfin
    readOnly: false

volumes:
  - name: jellyfin-media
    nfs:
      server: 172.16.20.98
      path: /nfs/Plex
      readOnly: false